In [25]:
import pandas as pd
import numpy as np

col = ['food', 'price', 'rating']
data = ['KFC', 1000, '4.5'], ['McDonald', 2000, '3.9'], ['SchoolFood', 2500, '4.2']
df = pd.DataFrame(data=data, columns=col)
df

         food  price rating
0         KFC   1000    4.5
1    McDonald   2000    3.9
2  SchoolFood   2500    4.2

In [28]:
df[['food','rating']]

         food rating
0         KFC    4.5
1    McDonald    3.9
2  SchoolFood    4.2

In [1]:
df2 = df.rename(columns={'food':'place'})
df2

NameError: name 'df' is not defined