In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./titanic/train.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
df.head(1)
df.tail(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [4]:
df.info()   #Non-Null Count 를 보고 누락된 데이터를 알 수 있다.

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [5]:
df.isna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [6]:
df.describe() #수치 컬럼 확인

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [7]:
df.describe(include='all')   #비수치 컬럼까지 다 보여줌

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,347082,NaN,G6,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

In [8]:
#df.corr()

In [9]:
df["SibSp"].corr(df["Parch"])  #문자로된 데이터는 학습에 바로 사용이 안됨. corr(df["문자열 포함 정보]") 오류남 -> 숫자로 변환 후 사용

np.float64(0.41483769862015646)

In [10]:
df.corr(numeric_only=True)

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
PassengerId,1.000000,-0.005007,-0.035144,0.036847,-0.057527,-0.001652,0.012658
Survived,-0.005007,1.000000,-0.338481,-0.077221,-0.035322,0.081629,0.257307
Pclass,-0.035144,-0.338481,1.000000,-0.369226,0.083081,0.018443,-0.549500
Age,0.036847,-0.077221,-0.369226,1.000000,-0.308247,-0.189119,0.096067
SibSp,-0.057527,-0.035322,0.083081,-0.308247,1.000000,0.414838,0.159651
Parch,-0.001652,0.081629,0.018443,-0.189119,0.414838,1.000000,0.216225
Fare,0.012658,0.257307,-0.549500,0.096067,0.159651,0.216225,1.000000

In [11]:
df.select_dtypes(include='number').corr()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
PassengerId,1.000000,-0.005007,-0.035144,0.036847,-0.057527,-0.001652,0.012658
Survived,-0.005007,1.000000,-0.338481,-0.077221,-0.035322,0.081629,0.257307
Pclass,-0.035144,-0.338481,1.000000,-0.369226,0.083081,0.018443,-0.549500
Age,0.036847,-0.077221,-0.369226,1.000000,-0.308247,-0.189119,0.096067
SibSp,-0.057527,-0.035322,0.083081,-0.308247,1.000000,0.414838,0.159651
Parch,-0.001652,0.081629,0.018443,-0.189119,0.414838,1.000000,0.216225
Fare,0.012658,0.257307,-0.549500,0.096067,0.159651,0.216225,1.000000

In [12]:
df[["SibSp", "Parch", "Fare"]].corr()

          SibSp     Parch      Fare
SibSp  1.000000  0.414838  0.159651
Parch  0.414838  1.000000  0.216225
Fare   0.159651  0.216225  1.000000

In [13]:
df.mean(numeric_only=True)

PassengerId    446.000000
Survived         0.383838
Pclass           2.308642
Age             29.699118
SibSp            0.523008
Parch            0.381594
Fare            32.204208
dtype: float64

In [14]:
df.groupby("Survived").mean(numeric_only=True)

          PassengerId    Pclass        Age     SibSp     Parch       Fare
Survived
0          447.016393  2.531876  30.626179  0.553734  0.329690  22.117887
1          444.368421  1.950292  28.343690  0.473684  0.464912  48.395408

In [15]:
df.groupby(['Sex', 'Survived']).mean(numeric_only=True)

                 PassengerId    Pclass        Age     SibSp     Parch  \
Sex    Survived
female 0          434.851852  2.851852  25.046875  1.209877  1.037037
       1          429.699571  1.918455  28.847716  0.515021  0.515021
male   0          449.121795  2.476496  31.618056  0.440171  0.207265
       1          475.724771  2.018349  27.276022  0.385321  0.357798

                      Fare
Sex    Survived
female 0         23.024385
       1         51.938573
male   0         21.960993
       1         40.821484

In [16]:
df1 =df.rename({"name":'이름'}, axis=1)   #axis는 축 방향 
df1.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [17]:
df2 = df.rename(columns={'age':'나이'})
df2.head(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [18]:
df3 = df.Sex.map(lambda x : 0 if x == "female" else 1)
df3.head()

0    1
1    0
2    0
3    0
4    1
Name: Sex, dtype: int64

In [19]:
def n_square(x):
    return x ** 2

In [20]:
df4_1 = df["Age"].map(n_square)
df4_1

0       484.0
1      1444.0
2       676.0
3      1225.0
4      1225.0
        ...
886     729.0
887     361.0
888       NaN
889     676.0
890    1024.0
Name: Age, Length: 891, dtype: float64

In [21]:
def n_square(x, n):
    return x ** n

In [22]:
df4 = df[["Age", "SibSp", "Fare"]].apply(n_square, n=2)
df4

        Age  SibSp         Fare
0     484.0      1    52.562500
1    1444.0      1  5081.308859
2     676.0      0    62.805625
3    1225.0      1  2819.610000
4    1225.0      0    64.802500
..      ...    ...          ...
886   729.0      0   169.000000
887   361.0      0   900.000000
888     NaN      1   549.902500
889   676.0      0   900.000000
890  1024.0      0    60.062500

[891 rows x 3 columns]

In [23]:
##객체연산

In [24]:
data = [[1,10,190],[2,29,200],[3,30,300]]
col = ['col1', 'col2', 'col3']
row = ['row1', 'row2', 'row3']
df = pd.DataFrame(data, row, col)
df

      col1  col2  col3
row1     1    10   190
row2     2    29   200
row3     3    30   300

In [25]:
result = df.add(1)
result

      col1  col2  col3
row1     2    11   191
row2     3    30   201
row3     4    31   301

In [26]:
data2 = [[3], [4], [5]]
df2 = pd.DataFrame(data=data2, index=['row1','row2','row3'], columns=['col1'])
df2

      col1
row1     3
row2     4
row3     5

In [27]:
result = df.add(df2)
result

      col1  col2  col3
row1     4   NaN   NaN
row2     6   NaN   NaN
row3     8   NaN   NaN

In [28]:
result = df.add(df2,fill_value=0) #df2에 없는 컬럼에 0을 채워서 연산
result

      col1  col2   col3
row1     4  10.0  190.0
row2     6  29.0  200.0
row3     8  30.0  300.0

In [29]:
result = df.add(1) #sub(), mul(), div(), mod()
result

      col1  col2  col3
row1     2    11   191
row2     3    30   201
row3     4    31   301

In [30]:
col = ['col1', 'col2']
row = ['row1', 'row2']
data1 = [[1,2],[3,4]]
data2 = [[5,6],[7,8]]
df1 = pd.DataFrame(data=data1)
df2 = pd.DataFrame(data=data2)

In [31]:
df1

   0  1
0  1  2
1  3  4

In [32]:
df2

   0  1
0  5  6
1  7  8

In [33]:
df3 = df1.dot(df2)
df3

    0   1
0  19  22
1  43  50

import numpy as np

col = ['col1', 'col2', 'col3']
row = ['row1', 'row2', 'row3']
data = np*random.rand(3,3)*100
df = pd.DataFrame(data=data, index=row, columns=col)
df

df.round(0)
df.round(2)

In [34]:
import numpy as np

col = ['col1', 'col2', 'col3']
row = ['row1', 'row2', 'row3']
data = np.random.rand(3,3)*100
df = pd.DataFrame(data=data, index=row, columns=col)
df

           col1       col2       col3
row1  76.942760  96.423270  69.980490
row2  41.337284  97.062709  59.269492
row3  30.440174  76.300811  31.204783

In [35]:
import numpy as np

col = ['col1', 'col2', 'col3']
row = ['row1', 'row2', 'row3']
data = [[1, 2, 3], [4, 5, 6], [7, np.nan, 9]]
df = pd.DataFrame(data=data, index=row, columns=col)
df

      col1  col2  col3
row1     1   2.0     3
row2     4   5.0     6
row3     7   NaN     9

In [36]:
df.sum(axis=0) #보통 0이면 행

col1    12.0
col2     7.0
col3    18.0
dtype: float64

In [37]:
df.sum(axis=1) # 1은 열이다.

row1     6.0
row2    15.0
row3    16.0
dtype: float64

In [38]:
df.sum(axis=0, skipna=False)

col1    12.0
col2     NaN
col3    18.0
dtype: float64

In [39]:
df.prod(axis=0) #nan 빼고 곱한거

col1     28.0
col2     10.0
col3    162.0
dtype: float64

In [40]:
df.prod(axis=1) #nan 빼고 곱한거

row1      6.0
row2    120.0
row3     63.0
dtype: float64

In [41]:
df.prod(axis=0, skipna=False) #nan도 곱한거

col1     28.0
col2      NaN
col3    162.0
dtype: float64

In [42]:
df.transpose()  #행 열 바꾸는거

      row1  row2  row3
col1   1.0   4.0   7.0
col2   2.0   5.0   NaN
col3   3.0   6.0   9.0

In [43]:
df.T

      row1  row2  row3
col1   1.0   4.0   7.0
col2   2.0   5.0   NaN
col3   3.0   6.0   9.0

In [44]:
idx=['A','A','B','B','B','C','C','C','D','D','D','D','E','E','E']
col=['col1', 'col2', 'col3']
data = np.random.randint(0,9,(15,3)) #data를 15행3열로 만들겠다는 뜻
df = pd.DataFrame(data=data, index=idx, columns=col).reset_index() #인덱스를 새로 부여하겠다는 뜻 reset_index
df

   index  col1  col2  col3
0      A     4     5     2
1      A     1     7     5
2      B     6     4     8
3      B     8     6     8
4      B     5     3     6
5      C     6     3     1
6      C     3     2     1
7      C     4     6     4
8      D     4     6     6
9      D     1     4     7
10     D     4     6     8
11     D     6     3     8
12     E     4     8     6
13     E     8     3     0
14     E     1     8     8

In [45]:
df.groupby('index').mean()

           col1      col2      col3
index
A      2.500000  6.000000  3.500000
B      6.333333  4.333333  7.333333
C      4.333333  3.666667  2.000000
D      3.750000  4.750000  7.250000
E      4.333333  6.333333  4.666667

In [46]:
df.groupby('index').count()

       col1  col2  col3
index
A         2     2     2
B         3     3     3
C         3     3     3
D         4     4     4
E         3     3     3

In [47]:
df.groupby('index').agg(['sum','mean']) #sum은 함수 이름~?

      col1           col2           col3
       sum      mean  sum      mean  sum      mean
index
A        5  2.500000   12  6.000000    7  3.500000
B       19  6.333333   13  4.333333   22  7.333333
C       13  4.333333   11  3.666667    6  2.000000
D       15  3.750000   19  4.750000   29  7.250000
E       13  4.333333   19  6.333333   14  4.666667

In [48]:
period = pd.period_range(start='2022-01-13 00:00:00', end='2022-01-13 02:30:00', freq='30min') #freq start-end까지 30분 단위로 
data = {'col1' :[1, 2, 3, 4, 5, 6], 'col2':period}
idx = ['row1', 'row2', 'row3', 'row4', 'row5', 'row6']
df = pd.DataFrame(data=data, index=idx)
df

      col1              col2
row1     1  2022-01-13 00:00
row2     2  2022-01-13 00:30
row3     3  2022-01-13 01:00
row4     4  2022-01-13 01:30
row5     5  2022-01-13 02:00
row6     6  2022-01-13 02:30

In [49]:
df.rolling(window=3).sum(numeric_only=True) #rolling -> 어떤 값을 주고

      col1
row1   NaN
row2   NaN
row3   6.0
row4   9.0
row5  12.0
row6  15.0

In [50]:
data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", '경상권'],
    "2010-2015 증가율" : [0.0283, 0.0163, 0.0982, 0.0141]
}

column_list = ['지역', '2015', '2010', '2005', '2000' , "2010-2015 증가율" ]
index_list = ['서울', '부산', '인천', '대구']
df = pd.DataFrame(data, index=index_list, columns = column_list)
df

     지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [51]:
df.index

Index(['서울', '부산', '인천', '대구'], dtype='str')

In [52]:
df.index.name = "도시"
df.columns.name = "특성"
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [53]:
df.T

도시                  서울       부산       인천       대구
특성
지역                 수도권      경상권      수도권      경상권
2015           9904312  3448737  2890451  2466052
2010           9631482  3393191  2632035  2431774
2005           9762546  3512547  2517680  2456016
2000           9853972  3655437  2466338  2473990
2010-2015 증가율   0.0283   0.0163   0.0982   0.0141

In [54]:
df["지역"]
#df["서울"] 로 쓰면 오류 왜?

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: str

In [55]:
df.지역  #컬럼명 정할 때 절대로 공백 사용하지 말자!

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: str

In [56]:
df[["2010", "2015"]]

특성     2010     2015
도시
서울  9631482  9904312
부산  3393191  3448737
인천  2632035  2890451
대구  2431774  2466052

In [57]:
df[["지역"]]

특성   지역
도시
서울  수도권
부산  경상권
인천  수도권
대구  경상권

In [58]:
type(df[['지역']])

pandas.DataFrame

In [59]:
type(df["지역"])

pandas.Series

In [60]:
import numpy as np

df2 = pd.DataFrame(np.arange(12).reshape(3, 4)) #np.arange()와 rnage() 함수는 동일하게 동작함. reshape은 구조를 바꿀 때 
df2

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [61]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [62]:
np.arange(12).reshape(6, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [63]:
df2[2] #열 1개?? 여기 헷갈리니까 다시 공부

0     2
1     6
2    10
Name: 2, dtype: int64

In [64]:
df["2010-2015 증가율"] = df["2010-2015 증가율"]*100
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972           2.83
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82
대구  경상권  2466052  2431774  2456016  2473990           1.41

In [65]:
df["2010-2015 증가율"] = ((df['2010'] - df['2005']) / df['2005'] * 100).round(2)
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54
대구  경상권  2466052  2431774  2456016  2473990          -0.99

In [66]:
del df["2010-2015 증가율"]  #df.drop("2010-2015 증가율", axis=1)
df

특성   지역     2015     2010     2005     2000
도시
서울  수도권  9904312  9631482  9762546  9853972
부산  경상권  3448737  3393191  3512547  3655437
인천  수도권  2890451  2632035  2517680  2466338
대구  경상권  2466052  2431774  2456016  2473990

In [67]:
df3 = df.drop("2005-2010 증가율", axis=1)
df3

KeyError: "['2005-2010 증가율'] not found in axis"

In [ ]:
df3 = df.drop("서울", axis=0)
df3

In [ ]:
#열과 행 인덱스 순서.   라벨을 통해서 접근할 때는 열 먼저 그 다음이 행
df['2015']['서울']

In [ ]:
df[1:3]

In [ ]:
df["서울":"부산"]

In [ ]:
df.iloc[[0,2]] #0행과 2행

In [ ]:
df.iloc[0:2] #0부터 2까지

In [ ]:
df.loc [["서울", "부산"]]

In [ ]:
df.loc["서울":"부산"]

In [ ]:
df = pd.DataFrame({"A":[1, 4, 7], "B":[2, 5, 8], "C":[3, 6, 9]})
df

In [ ]:
df.iloc[0] # illoc와 loc() 로 접근할 때는 행 열 순서이다 데이터 프레임과 다르다. 행의 0을 가리킴

In [ ]:
df.iloc[[0,2]]

In [ ]:
print(df.iloc[0])  #라벨명 지칭

In [ ]:
df.loc[:,'A']

In [ ]:
df['A']

In [ ]:
#df[0] 순서가 열 행이니 에러뜸

In [ ]:
df.loc[0]['B']

In [ ]:
df['B'][0]

In [68]:
import pandas as pd
import numpy as np

df = pd.DataFrame([[1,2,3], [4,5,6], [7,8,9]], index=['row1', 'row2', 'row3'],
                  columns=['col1','col2', 'col3'])
df

      col1  col2  col3
row1     1     2     3
row2     4     5     6
row3     7     8     9

In [69]:
df

      col1  col2  col3
row1     1     2     3
row2     4     5     6
row3     7     8     9

In [70]:
result = df.loc['row1']
result

col1    1
col2    2
col3    3
Name: row1, dtype: int64

In [71]:
result = df.loc[['row1','row2']]
result

      col1  col2  col3
row1     1     2     3
row2     4     5     6

In [72]:
result = df.loc['row1':'row3','col2']
result

row1    2
row2    5
row3    8
Name: col2, dtype: int64

In [73]:
bool2 = [False, True, False]
result = df.loc[bool2]
result

      col1  col2  col3
row2     4     5     6

In [74]:
result = df.loc[df['col3'] > 5]
result

      col1  col2  col3
row2     4     5     6
row3     7     8     9

In [75]:
result = df.loc[  df['col3'] > 5, ['col2']  ]
result

      col2
row2     5
row3     8

In [76]:
result = df.loc[lambda df : df['col2'] == 5]
result

      col1  col2  col3
row2     4     5     6

In [77]:
df.loc[  ['row1', 'row3'], ['col3']  ] = 10
df

      col1  col2  col3
row1     1     2    10
row2     4     5     6
row3     7     8    10

In [78]:
# df.loc[  :  ,  ['col3']  ] = 'B' #데이터 타입의 변화는 허용되지 않는다 ,, loc 빼고하면 된다!

In [79]:
result = df.select_dtypes(include=[bool, float])
result

Empty DataFrame
Columns: []
Index: [row1, row2, row3]

In [80]:
index_tuples = [('row1', 'val1'), ('row1', 'val2'), ('row2','val1'), ('row2', 'val2'),
            ('row2', 'val3'), ('row3', 'val2'), ('row3', 'val3')]
values = [  [1,2,3], [4,5,6], [7,8,9] , [10,11,12], [13,14,15], [16,17,18], [19,20,21] ]
index = pd.MultiIndex.from_tuples(index_tuples) #인덱스 설정
df = pd.DataFrame(values, columns=['col1','col2','col3'], index = index)
df

#인덱스 만들 때 from Tuples *참고 !

           col1  col2  col3
row1 val1     1     2     3
     val2     4     5     6
row2 val1     7     8     9
     val2    10    11    12
     val3    13    14    15
row3 val2    16    17    18
     val3    19    20    21

In [81]:
result = df.loc['row2']
result

      col1  col2  col3
val1     7     8     9
val2    10    11    12
val3    13    14    15

In [82]:
result = df.loc[[('row2', 'val2')]]  #첫 번째 레벨, 두 번째 레벨 순 !!
result

           col1  col2  col3
row2 val2    10    11    12

In [83]:
result = df.loc[('row2','val2'), 'col3']
result

np.int64(12)

In [84]:
result = df.loc[('row1','val2')  :  ('row3', 'val2')]
result

           col1  col2  col3
row1 val2     4     5     6
row2 val1     7     8     9
     val2    10    11    12
     val3    13    14    15
row3 val2    16    17    18

In [85]:
#열

import pandas as pd
data = [ 
    [100, 900, 800, 700],
    [1200, 1400, 900, 800]
]

columns=[
    ['영업이익', '영업이익', '당기순이익', '당기순이익'],     # 첫번째 레벨
     ['컨센서스', '잠정치', '컨센서스', '잠정치']   #두번쨰레벨
]
index = ["2020/06", "2020/09"]
df = pd.DataFrame(data=data, index=index, columns=columns)
df

         영업이익       당기순이익
         컨센서스   잠정치  컨센서스  잠정치
2020/06   100   900   800  700
2020/09  1200  1400   900  800

In [86]:
import pandas as pd
data = [
    [100, 900, 800, 700],
    [1200, 1400, 900, 800]
]
index = ["2020/06", "2020/09"]
level_0 = ["영업이익", " 당기순이익"]
level_1 = ["컨센서스", "잠정치"]
idx = pd.MultiIndex.from_product([level_0, level_1])
df = pd.DataFrame(data=data, index=index, columns=idx)
df

         영업이익        당기순이익
         컨센서스   잠정치   컨센서스  잠정치
2020/06   100   900    800  700
2020/09  1200  1400    900  800

In [87]:
import io
import pandas as pd

csv = '''
   	A팀		B팀		C팀	
	삼성전자	카카오	삼성전자	카카오	삼성전자	카카오
2023-08-14	10	20	30	40	50	60
2023-08-16	20	20	30	40	50	60
2023-08-17	30	40	10	20	50	60
2023-08-18	30	40	10	20	50	60
2023-08-21	30	40	30	40	30	40
'''

df_csv = pd.read_csv(io.StringIO(csv), sep='\t', index_col=0, header=[0, 1])  #문자열을 파일처럼 다룰 수 있는 io.StringIO이다. index_col 0번째 행을 인덱스로 사용하겠다
df_csv

#헤더로 0번째 ? 가냥

,A팀,Unnamed: 2_level_0,B팀,Unnamed: 4_level_0,C팀,Unnamed: 6_level_0
,삼성전자,카카오,삼성전자,카카오,삼성전자,카카오
2023-08-14,10,20,30,40,50,60
2023-08-16,20,20,30,40,50,60
2023-08-17,30,40,10,20,50,60
2023-08-18,30,40,10,20,50,60
2023-08-21,30,40,30,40,30,40

In [88]:
df1 = df_csv.columns.to_frame(index=False).apply(lambda x: x.mask(x.str.contains('Unnamed'))).ffill()
df_csv = df_csv.set_axis(pd.MultiIndex.from_frame(df1, names=[''] * len(df_csv.columns[0])), axis=1)
df_csv

             A팀       B팀       C팀
           삼성전자 카카오 삼성전자 카카오 삼성전자 카카오
2023-08-14   10  20   30  40   50  60
2023-08-16   20  20   30  40   50  60
2023-08-17   30  40   10  20   50  60
2023-08-18   30  40   10  20   50  60
2023-08-21   30  40   30  40   30  40

In [89]:
df1

          1
0  A팀  삼성전자
1  A팀   카카오
2  B팀  삼성전자
3  B팀   카카오
4  C팀  삼성전자
5  C팀   카카오

In [90]:
df

         영업이익        당기순이익
         컨센서스   잠정치   컨센서스  잠정치
2020/06   100   900    800  700
2020/09  1200  1400    900  800

In [91]:
df["영업이익"]

         컨센서스   잠정치
2020/06   100   900
2020/09  1200  1400

In [92]:
df[[("영업이익","컨센서스")]] #상위레벨 영업이익, 하위레벨 컨센서스로 생각.

         영업이익
         컨센서스
2020/06   100
2020/09  1200

In [93]:
df.loc["2020/06", "영업이익"]

컨센서스    100
잠정치     900
Name: 2020/06, dtype: int64

In [94]:
df.loc[["2020/06"], ["영업이익"]]

        영업이익
        컨센서스  잠정치
2020/06  100  900

In [95]:
df.loc["2020/06", ("영업이익","컨센서스")]

np.int64(100)

In [96]:
#slice(None) : [:] 슬라이스와 동일한 의미, 멀티 인덱스의 특정 레베 랜의 모든 값
df.loc["2020/06", (slice(None), "컨센서스")]

영업이익    컨센서스    100
 당기순이익  컨센서스    800
Name: 2020/06, dtype: int64

In [97]:
df.loc[["2020/06"], (slice(None),"컨센서스")]

        영업이익  당기순이익
        컨센서스   컨센서스
2020/06  100    800

In [98]:
df2 = df.T #정리하는 애
df2

             2020/06  2020/09
영업이익   컨센서스      100     1200
       잠정치       900     1400
 당기순이익 컨센서스      800      900
       잠정치       700      800

In [99]:
df2.loc[("영업이익", "컨센서스")]

2020/06     100
2020/09    1200
Name: (영업이익, 컨센서스), dtype: int64

In [100]:
df2.loc[("영업이익", "컨센서스"), "2020/06"]

np.int64(100)

In [101]:
df2.loc[[("영업이익", "컨센서스")], "2020/06"]

영업이익  컨센서스    100
Name: 2020/06, dtype: int64

In [102]:
df2.loc[[("영업이익", "컨센서스")], ["2020/06"]]

           2020/06
영업이익 컨센서스      100

In [103]:
df2.loc[(slice(None), "컨센서스"),:]

             2020/06  2020/09
영업이익   컨센서스      100     1200
 당기순이익 컨센서스      800      900

In [104]:
col1 = [1, 2, 3, 4, 5]
col2 = ['one', 'two', 'three', ' four', 'five']
col3 = [1.5, 2.5, 3.5, 4.5, 5.5]
col4 = [True, False, False, True, True]
df = pd.DataFrame({"col1": col1, "col2":col2, "col3":col3, "col4":col4})
df

   col1   col2  col3   col4
0     1    one   1.5   True
1     2    two   2.5  False
2     3  three   3.5  False
3     4   four   4.5   True
4     5   five   5.5   True

In [105]:
df.dtypes

col1      int64
col2        str
col3    float64
col4       bool
dtype: object

In [106]:
result = df.select_dtypes(include=float)
result

   col3
0   1.5
1   2.5
2   3.5
3   4.5
4   5.5

In [107]:
result = df.select_dtypes(include=['bool', 'float'])
result

   col3   col4
0   1.5   True
1   2.5  False
2   3.5  False
3   4.5   True
4   5.5   True

In [108]:
result = df.select_dtypes(exclude=['int64'])
result

    col2  col3   col4
0    one   1.5   True
1    two   2.5  False
2  three   3.5  False
3   four   4.5   True
4   five   5.5   True

In [109]:
col = ['alpha', 'beta', 'gamma', 'delta', 'epsilon']
row = ['sigma', 'omega', 'lambda']
data = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
df = pd.DataFrame(data,row,col)
df

        alpha  beta  gamma  delta  epsilon
sigma       1     2      3      4        5
omega       6     7      8      9       10
lambda     11    12     13     14       15

In [110]:
df.filter(items=['alpha', 'delta'])

        alpha  delta
sigma       1      4
omega       6      9
lambda     11     14

In [111]:
df.filter(items=['omega'],axis=0)  #오메가는 행

       alpha  beta  gamma  delta  epsilon
omega      6     7      8      9       10

In [112]:
df.filter(regex='[nm]')

        gamma  epsilon
sigma       3        5
omega       8       10
lambda     13       15

In [113]:
df.filter(regex='^g')

        gamma
sigma       3
omega       8
lambda     13

In [114]:
df.filter(regex='a$')  #a로 끝나는 라벨 값들을 모두 출력.

        alpha  beta  gamma  delta
sigma       1     2      3      4
omega       6     7      8      9
lambda     11    12     13     14

In [115]:
df.dtypes

alpha      int64
beta       int64
gamma      int64
delta      int64
epsilon    int64
dtype: object

In [116]:
import pandas as pd

df = pd.read_csv('./titanic/train.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [117]:
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [118]:
df[["Name", "Age", "Sex", "Survived"]]

                                                  Name   Age     Sex  Survived
0                              Braund, Mr. Owen Harris  22.0    male         0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female         1
2                               Heikkinen, Miss. Laina  26.0  female         1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female         1
4                             Allen, Mr. William Henry  35.0    male         0
..                                                 ...   ...     ...       ...
886                              Montvila, Rev. Juozas  27.0    male         0
887                       Graham, Miss. Margaret Edith  19.0  female         1
888           Johnston, Miss. Catherine Helen "Carrie"   NaN  female         0
889                              Behr, Mr. Karl Howell  26.0    male         1
890                                Dooley, Mr. Patrick  32.0    male         0

[891 rows x 4 columns]

In [119]:
mask = (df["Sex"] == "female")
mask

0      False
1       True
2       True
3       True
4      False
       ...
886    False
887     True
888     True
889    False
890    False
Name: Sex, Length: 891, dtype: bool

In [120]:
df[mask]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [121]:
df[df["Sex"] == "female"]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [122]:
df9 = df[df['PassengerId'] == 3]['Name']
df9

2    Heikkinen, Miss. Laina
Name: Name, dtype: str

In [123]:
df9.values

<StringArray>
['Heikkinen, Miss. Laina']
Length: 1, dtype: str

In [124]:
df['family'] = df["SibSp"] + df["Parch"]
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,family
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1

In [125]:
df = pd.DataFrame({"A":[1,4,7], "B":[2,5,8], "C":[3,6,9]})
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [126]:
df = df.set_index('A')
df

   B  C
A
1  2  3
4  5  6
7  8  9

In [127]:
df = pd.DataFrame(data=np.array([[1,2,3], [4,5,6], [7,8,9]] ),
                  columns = [48, 49, 50])
df

   48  49  50
0   1   2   3
1   4   5   6
2   7   8   9

In [128]:
a = pd.DataFrame(data=[[1,2,3]], columns=[48,49,50])
a

   48  49  50
0   1   2   3

In [129]:
df = pd.concat([df,a])
df

   48  49  50
0   1   2   3
1   4   5   6
2   7   8   9
0   1   2   3

In [130]:
df2 = df.reset_index(drop=True) #TRue가 일반적인 방식.
df2

   48  49  50
0   1   2   3
1   4   5   6
2   7   8   9
3   1   2   3

In [131]:
df2 = df.reset_index(drop=False)
df2

   index  48  49  50
0      0   1   2   3
1      1   4   5   6
2      2   7   8   9
3      0   1   2   3

In [132]:
df = pd.DataFrame(data=np.array([[1,2,3], [4,5,6], [7,8,9]]),
                  columns = ['A', 'B', 'C'])
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [133]:
df2 = df.drop('A', axis=1, inplace=False)
df2

   B  C
0  2  3
1  5  6
2  8  9

In [134]:
df2

   B  C
0  2  3
1  5  6
2  8  9

In [135]:
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [136]:
df.drop('A', axis=1, inplace=True)
df

   B  C
0  2  3
1  5  6
2  8  9

In [137]:
df.drop('B', axis=1)   # 값이 False가 됐다.
df

   B  C
0  2  3
1  5  6
2  8  9

In [138]:
df.drop(2, axis=0, inplace=True)
df

   B  C
0  2  3
1  5  6

In [139]:
df = pd.DataFrame(data=np.array([[1,2,3], [4,5,6], [7,8,9]]),
                  columns = ['A', 'B', 'C'])
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [140]:
df2 = df.drop([0,2], axis = 0, inplace=False)
df2

   A  B  C
1  4  5  6

In [141]:
df2 = df.drop(['A', 'C'], axis=1, inplace=False)
df2

   B
0  2
1  5
2  8

In [142]:
df = pd.DataFrame(data=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [40, 50, 60], [23, 35, 37]]),
                  index = [2.5, 12.6, 4.8, 4.8, 2.5],
                  columns = [48, 49, 50])
df

      48  49  50
2.5    1   2   3
12.6   4   5   6
4.8    7   8   9
4.8   40  50  60
2.5   23  35  37

In [143]:
df = df.reset_index()
df

   index  48  49  50
0    2.5   1   2   3
1   12.6   4   5   6
2    4.8   7   8   9
3    4.8  40  50  60
4    2.5  23  35  37

In [144]:
df2 = df.drop_duplicates(subset='index', keep=False).set_index('index')
df2

       48  49  50
index
12.6    4   5   6

In [145]:
df = pd.DataFrame(data=np.array([[1,2,3], [1,5,6], [7,8,9]]),
                  columns = ['A', 'B', 'C'], index=[11,22,33])
df

    A  B  C
11  1  2  3
22  1  5  6
33  7  8  9

In [146]:
df.index[1] # ㅔ[ㅜ]-> ㅜ를가르킴

np.int64(22)

In [147]:
df2 = df.drop(df.index[1])
df2

    A  B  C
11  1  2  3
33  7  8  9

In [148]:
df2 = df.drop(22)
df2

    A  B  C
11  1  2  3
33  7  8  9

In [149]:
df2 = df.drop(df.index[1], axis=0)
df2

    A  B  C
11  1  2  3
33  7  8  9

In [150]:
df2 = df.drop(22)
df2

    A  B  C
11  1  2  3
33  7  8  9

In [151]:
col = ['col1', 'col2', 'col3', 'col4', 'col5']
row = ['row1', 'row2', 'row3', 'row4']
data = [[1,2,3,pd.NA,5], [6,pd.NA,8,pd.NA,10],[11,12,13,14,15],[pd.NA,pd.NA,pd.NA,pd.NA,pd.NA]]
df = pd.DataFrame(data, row, col)
df

      col1  col2  col3  col4  col5
row1     1     2     3  <NA>     5
row2     6  <NA>     8  <NA>    10
row3    11    12    13    14    15
row4  <NA>  <NA>  <NA>  <NA>  <NA>

In [152]:
df2 =  df.dropna(axis=0)
df2

     col1 col2 col3 col4 col5
row3   11   12   13   14   15

In [153]:
df2 =  df.dropna(axis=1)
df2

Empty DataFrame
Columns: []
Index: [row1, row2, row3, row4]

In [154]:
df2 = df.dropna(how='any', axis=0)
df2

     col1 col2 col3 col4 col5
row3   11   12   13   14   15

In [155]:
df2 = df.dropna(thresh = 3)
df2

     col1  col2 col3  col4 col5
row1    1     2    3  <NA>    5
row2    6  <NA>    8  <NA>   10
row3   11    12   13    14   15

In [156]:
df2 = df.dropna(thresh = 4)   # 제거할 대상이 된다? 뭐가 ?
df2

     col1 col2 col3  col4 col5
row1    1    2    3  <NA>    5
row3   11   12   13    14   15

In [157]:
df2 = df.dropna(subset=['col1','col2'])  # 두 개 의 컬럼을 기준으로 난?이 있는지 확인, col1 , col2 를 보고!!
df2

     col1 col2 col3  col4 col5
row1    1    2    3  <NA>    5
row3   11   12   13    14   15

In [158]:
df.dropna(subset=['col1', 'col2'], inplace=True)

In [159]:
df  #여기까지 NAn 데이터 지우는 것

     col1 col2 col3  col4 col5
row1    1    2    3  <NA>    5
row3   11   12   13    14   15

In [160]:
# NAN 데이터 채우는 것

col = ['col1','col2','col3','col4','col5']
row = ['row1','row2','row3','row4','row5']
na = np.nan
data = [[na, 2,na, 4,na],
        [ 6, 7,na, 9,na],
        [11,na,na,14,15],
        [na,17,na,na,20],
        [na,22,na,na,25]]
df = pd.DataFrame(data,row,col)
df

      col1  col2  col3  col4  col5
row1   NaN   2.0   NaN   4.0   NaN
row2   6.0   7.0   NaN   9.0   NaN
row3  11.0   NaN   NaN  14.0  15.0
row4   NaN  17.0   NaN   NaN  20.0
row5   NaN  22.0   NaN   NaN  25.0

In [161]:
df2 = df.fillna('A')  #전체 다 채우는것
df2

      col1  col2 col3  col4  col5
row1     A   2.0    A   4.0     A
row2   6.0   7.0    A   9.0     A
row3  11.0     A    A  14.0  15.0
row4     A  17.0    A     A  20.0
row5     A  22.0    A     A  25.0

In [162]:
dict = {'col1':'A','col2':'B','col3':'C', 'col4':'D', 'col5':'E'}
df.fillna(value=dict)

      col1  col2 col3  col4  col5
row1     A   2.0    C   4.0     E
row2   6.0   7.0    C   9.0     E
row3  11.0     B    C  14.0  15.0
row4     A  17.0    C     D  20.0
row5     A  22.0    C     D  25.0

In [163]:
df['col1'].fillna(100)

row1    100.0
row2      6.0
row3     11.0
row4    100.0
row5    100.0
Name: col1, dtype: float64

In [164]:
df1 = pd.DataFrame({'고유번호': [1001, 1002, 1003, 1004, 1005, 1006, 1007],
                    '이름': ['둘리', '도우너', '또치', '길동', '희동', '마이클', '영희']},
                   columns=['고객번호', '이름'])
df1

  고객번호   이름
0  NaN   둘리
1  NaN  도우너
2  NaN   또치
3  NaN   길동
4  NaN   희동
5  NaN  마이클
6  NaN   영희

In [165]:
df2 = pd.DataFrame({'고유번호': [1001, 1002, 1003, 1004, 1005, 1006, 1007],
                    '금액': [10000, 20000, 15000, 5000, 100000, 30000]},
                   columns=['고객번호', '금액'])
df2

  고객번호      금액
0  NaN   10000
1  NaN   20000
2  NaN   15000
3  NaN    5000
4  NaN  100000
5  NaN   30000

In [166]:
df3 = pd.merge(df1,df2)  #공통된... 교집합의 개념
df3

   고객번호   이름      금액
0   NaN   둘리   10000
1   NaN   둘리   20000
2   NaN   둘리   15000
3   NaN   둘리    5000
4   NaN   둘리  100000
5   NaN   둘리   30000
6   NaN  도우너   10000
7   NaN  도우너   20000
8   NaN  도우너   15000
9   NaN  도우너    5000
10  NaN  도우너  100000
11  NaN  도우너   30000
12  NaN   또치   10000
13  NaN   또치   20000
14  NaN   또치   15000
15  NaN   또치    5000
16  NaN   또치  100000
17  NaN   또치   30000
18  NaN   길동   10000
19  NaN   길동   20000
20  NaN   길동   15000
21  NaN   길동    5000
22  NaN   길동  100000
23  NaN   길동   30000
24  NaN   희동   10000
25  NaN   희동   20000
26  NaN   희동   15000
27  NaN   희동    5000
28  NaN   희동  100000
29  NaN   희동   30000
30  NaN  마이클   10000
31  NaN  마이클   20000
32  NaN  마이클   15000
33  NaN  마이클    5000
34  NaN  마이클  100000
35  NaN  마이클   30000
36  NaN   영희   10000
37  NaN   영희   20000
38  NaN   영희   15000
39  NaN   영희    5000
40  NaN   영희  100000
41  NaN   영희   30000

In [167]:
df4 = pd.merge(df1, df2, how='outer')
df4

   고객번호   이름      금액
0   NaN   둘리   10000
1   NaN   둘리   20000
2   NaN   둘리   15000
3   NaN   둘리    5000
4   NaN   둘리  100000
5   NaN   둘리   30000
6   NaN  도우너   10000
7   NaN  도우너   20000
8   NaN  도우너   15000
9   NaN  도우너    5000
10  NaN  도우너  100000
11  NaN  도우너   30000
12  NaN   또치   10000
13  NaN   또치   20000
14  NaN   또치   15000
15  NaN   또치    5000
16  NaN   또치  100000
17  NaN   또치   30000
18  NaN   길동   10000
19  NaN   길동   20000
20  NaN   길동   15000
21  NaN   길동    5000
22  NaN   길동  100000
23  NaN   길동   30000
24  NaN   희동   10000
25  NaN   희동   20000
26  NaN   희동   15000
27  NaN   희동    5000
28  NaN   희동  100000
29  NaN   희동   30000
30  NaN  마이클   10000
31  NaN  마이클   20000
32  NaN  마이클   15000
33  NaN  마이클    5000
34  NaN  마이클  100000
35  NaN  마이클   30000
36  NaN   영희   10000
37  NaN   영희   20000
38  NaN   영희   15000
39  NaN   영희    5000
40  NaN   영희  100000
41  NaN   영희   30000

In [168]:
df5 = pd.merge(df1, df2, how='left')
df5

   고객번호   이름      금액
0   NaN   둘리   10000
1   NaN   둘리   20000
2   NaN   둘리   15000
3   NaN   둘리    5000
4   NaN   둘리  100000
5   NaN   둘리   30000
6   NaN  도우너   10000
7   NaN  도우너   20000
8   NaN  도우너   15000
9   NaN  도우너    5000
10  NaN  도우너  100000
11  NaN  도우너   30000
12  NaN   또치   10000
13  NaN   또치   20000
14  NaN   또치   15000
15  NaN   또치    5000
16  NaN   또치  100000
17  NaN   또치   30000
18  NaN   길동   10000
19  NaN   길동   20000
20  NaN   길동   15000
21  NaN   길동    5000
22  NaN   길동  100000
23  NaN   길동   30000
24  NaN   희동   10000
25  NaN   희동   20000
26  NaN   희동   15000
27  NaN   희동    5000
28  NaN   희동  100000
29  NaN   희동   30000
30  NaN  마이클   10000
31  NaN  마이클   20000
32  NaN  마이클   15000
33  NaN  마이클    5000
34  NaN  마이클  100000
35  NaN  마이클   30000
36  NaN   영희   10000
37  NaN   영희   20000
38  NaN   영희   15000
39  NaN   영희    5000
40  NaN   영희  100000
41  NaN   영희   30000

In [169]:
df6 = pd.merge(df1, df2, how= 'rghit')
df6

ValueError: 'rghit' is not a valid Merge type: left, right, inner, outer, left_anti, right_anti, cross, asof

In [170]:
df1 = pd.DataFrame({
    '품종':['setosa', 'virginica', 'virginica', 'versicolor'],
    '꽃잎길이': [1.4, 1.3, 1.5, 1.3]},
    columns = ['품종', '꽃잎길이'])
df1

           품종  꽃잎길이
0      setosa   1.4
1   virginica   1.3
2   virginica   1.5
3  versicolor   1.3

In [171]:
df2 = pd.DataFrame({
    '품종':['setosa', 'virginica', 'virginica', 'versicolor'],
    '꽃잎너비': [0.4, 0.3, 0.5, 0.3]},
    columns = ['품종', '꽃잎너비'])
df2

           품종  꽃잎너비
0      setosa   0.4
1   virginica   0.3
2   virginica   0.5
3  versicolor   0.3

In [172]:
df3 = pd.merge(df1, df2) #왜 안나옴??
df3

           품종  꽃잎길이  꽃잎너비
0      setosa   1.4   0.4
1   virginica   1.3   0.3
2   virginica   1.3   0.5
3   virginica   1.5   0.3
4   virginica   1.5   0.5
5  versicolor   1.3   0.3

In [173]:
df1 = pd.DataFrame({
    '고객명' : ['춘향', '춘향', '몽룡'],
    '날짜' : ['2018-01-01', '2018-01-02', '2018-01-01'],
    '데이터' : ['20000', '30000', '100000']})
df1

  고객명          날짜     데이터
0  춘향  2018-01-01   20000
1  춘향  2018-01-02   30000
2  몽룡  2018-01-01  100000

In [174]:
df2 = pd.DataFrame({
    '고객명': ['춘향', '몽룡'],
    '데이터': ['여자', '남자']})
df2

  고객명 데이터
0  춘향  여자
1  몽룡  남자

In [175]:
df3 = pd.merge(df1, df2, on = '고객명')  #뒤에 -X, -Y는 정리사 구분지으려고,
df3

  고객명          날짜   데이터_x 데이터_y
0  춘향  2018-01-01   20000    여자
1  춘향  2018-01-02   30000    여자
2  몽룡  2018-01-01  100000    남자

In [176]:
df1 = pd.DataFrame({
    '고객명' : ['춘향', '춘향', '몽룡'],
    '날짜' : ['2018-01-01', '2018-01-02', '2018-01-01'],
    '데이터' : ['20000', '30000', '100000']})
df1

  고객명          날짜     데이터
0  춘향  2018-01-01   20000
1  춘향  2018-01-02   30000
2  몽룡  2018-01-01  100000

In [177]:
df2 = pd.DataFrame({
    '성명': ['춘향', '몽룡'],
    '데이터': ['여자', '남자']})
df2          #컬럼명이 다른 걸 머지하고 싶다면 각각 부여

   성명 데이터
0  춘향  여자
1  몽룡  남자

In [178]:
df3 = pd.merge(df1, df2, left_on='고객명', right_on='성명')
df3

  고객명          날짜   데이터_x  성명 데이터_y
0  춘향  2018-01-01   20000  춘향    여자
1  춘향  2018-01-02   30000  춘향    여자
2  몽룡  2018-01-01  100000  몽룡    남자

In [179]:
df1 = pd.DataFrame({'도시': ['서울', '서울', '서울', '부산', '부산'],
                    '연도': [2000, 2005, 2010, 2000, 2005],
                    '인구': [9853972, 9762546, 9631482, 3655437, 3512547]})
df1

   도시    연도       인구
0  서울  2000  9853972
1  서울  2005  9762546
2  서울  2010  9631482
3  부산  2000  3655437
4  부산  2005  3512547

In [180]:
df2 = pd.DataFrame(np.arange(12).reshape((6,2)),
                   index=[['부산', '부산', '서울', '서울', '서울', '서울'],
                          [2000, 2005, 2000, 2005, 2010, 2015]],
                   columns=['데이터1', '데이터2'])
df2

         데이터1  데이터2
부산 2000     0     1
   2005     2     3
서울 2000     4     5
   2005     6     7
   2010     8     9
   2015    10    11

In [181]:
df3 = pd.merge(df1, df2, left_on=['도시', '연도'], right_index=True)
df3

   도시    연도       인구  데이터1  데이터2
0  서울  2000  9853972     4     5
1  서울  2005  9762546     6     7
2  서울  2010  9631482     8     9
3  부산  2000  3655437     0     1
4  부산  2005  3512547     2     3

In [182]:
#비슷한 인덱스 기준으로 나열.
df1 = pd.DataFrame(
    [[1., 2.], [3., 4.], [5., 6.]],
    index=['a', 'c', 'e'],
    columns=['서울', '부산'])
df1

    서울   부산
a  1.0  2.0
c  3.0  4.0
e  5.0  6.0

In [183]:
df2 = pd.DataFrame(
    [[7., 8.], [9., 10.], [11., 12.], [13, 14]],
    index=['b', 'c', 'd', 'e'],
    columns=['대구', '광주'])
df2

     대구    광주
b   7.0   8.0
c   9.0  10.0
d  11.0  12.0
e  13.0  14.0

In [184]:
df3 = pd.merge(df1, df2, how='outer', left_index=True, right_index=True)
df3

    서울   부산    대구    광주
a  1.0  2.0   NaN   NaN
b  NaN  NaN   7.0   8.0
c  3.0  4.0   9.0  10.0
d  NaN  NaN  11.0  12.0
e  5.0  6.0  13.0  14.0

In [185]:
# index, solumn, value
df1.pivot(index="도시", columns="연도", values="인구")

KeyError: '도시'

In [186]:
df1.pivot(index="지역", columns="연도", values="인구")

KeyError: '지역'